apiVersion: v1
kind: Namespace
metadata:
  name: secret-watcher
spec: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-watcher
  namespace: secret-watcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-view
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-view-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-view
subjects:
- kind: ServiceAccount
  name: secret-watcher
  namespace: secret-watcher
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: secret-watcher
  name: secret-watcher
  namespace: secret-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-watcher
  strategy: {}
  template:
    metadata:
      labels:
        app: secret-watcher
    spec:
      serviceAccountName: secret-watcher
      containers:
      - image: cmwylie19/secret-watcher
        name: secret-watcher
        command:
        - ./secret-watcher
        - server
        - -p 
        - "8080"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: secret-watcher
  name: secret-watcher
  namespace: secret-watcher
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: secret-watcher